#!/bin/sh

NAME="opendicom-navigator"
GROUP="opendicom.net"

rm -Rf /usr/share/$GROUP/$NAME
rm -Rf /usr/share/doc/$GROUP/$NAME
rmdir --ignore-fail-on-non-empty /usr/share/$GROUP
rmdir --ignore-fail-on-non-empty /usr/share/doc/$GROUP
rm -f /usr/share/applications/dicom-file-navigator.desktop /usr/bin/dicom-file-navigator /usr/share/pixmaps/sextant.png

