#!/bin/sh

NAME="opendicom-sharp-gdk"
GROUP="opendicom.net"

rm -Rf /usr/lib/mono/$NAME
rm -Rf /usr/share/$GROUP/$NAME
rm -Rf /usr/share/doc/$GROUP/$NAME
rmdir --ignore-fail-on-non-empty /usr/share/$GROUP
rmdir --ignore-fail-on-non-empty /usr/share/doc/$GROUP
rm -f /usr/lib/pkgconfig/$NAME.pc

