// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Stetic {
    
    
    internal class Gui {
        
        public static void Build(object obj, System.Type type) {
            Stetic.Gui.Build(obj, type.FullName);
        }
        
        public static void Build(object obj, string id) {
            System.Collections.Hashtable bindings = new System.Collections.Hashtable();
            if ((id == "MainWindow")) {
                Gtk.Window cobj = ((Gtk.Window)(obj));
                // Widget MainWindow
                cobj.Title = "Gtk DICOM Viewer";
                Gtk.UIManager w1 = new Gtk.UIManager();
                Gtk.ActionGroup w2 = new Gtk.ActionGroup("Default");
                Gtk.Action w3 = new Gtk.Action("File", "File", null, null);
                w3.ShortLabel = "File";
                bindings["File"] = w3;
                w2.Add(w3, null);
                Gtk.Action w4 = new Gtk.Action("Open", "Open", null, "gtk-open");
                w4.ShortLabel = "Open";
                bindings["Open"] = w4;
                w2.Add(w4, null);
                Gtk.Action w5 = new Gtk.Action("Save", "Save", null, "gtk-save");
                w5.ShortLabel = "Save";
                bindings["Save"] = w5;
                w2.Add(w5, "<Control><Mod2>s");
                Gtk.Action w6 = new Gtk.Action("", "-", null, null);
                w6.ShortLabel = "-";
                bindings[""] = w6;
                w2.Add(w6, null);
                Gtk.Action w7 = new Gtk.Action("Quit", "Quit", null, "gtk-quit");
                w7.ShortLabel = "Quit";
                bindings["Quit"] = w7;
                w2.Add(w7, null);
                Gtk.Action w8 = new Gtk.Action("Help", "Help", null, null);
                w8.ShortLabel = "Help";
                bindings["Help"] = w8;
                w2.Add(w8, null);
                Gtk.Action w9 = new Gtk.Action("About", "About", null, null);
                w9.ShortLabel = "About";
                bindings["About"] = w9;
                w2.Add(w9, null);
                w1.InsertActionGroup(w2, 0);
                cobj.AddAccelGroup(w1.AccelGroup);
                cobj.WindowPosition = ((Gtk.WindowPosition)(4));
                cobj.Events = ((Gdk.EventMask)(0));
                cobj.Name = "MainWindow";
                // Container child MainWindow.Gtk.Container+ContainerChild
                Gtk.VBox w10 = new Gtk.VBox();
                w10.Events = ((Gdk.EventMask)(0));
                w10.Name = "vbox1";
                // Container child vbox1.Gtk.Box+BoxChild
                w1.AddUiFromString("<ui><menubar name='menubar1'><menu action='File'><menuitem action='Open'/><menuitem action='Save'/><separator/><menuitem action='Quit'/></menu><menu action='Help'><menuitem action='About'/></menu></menubar></ui>");
                Gtk.MenuBar w11 = ((Gtk.MenuBar)(w1.GetWidget("/menubar1")));
                w11.Events = ((Gdk.EventMask)(0));
                w11.Name = "menubar1";
                bindings["menubar1"] = w11;
                w10.Add(w11);
                Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(w10[w11]));
                w12.Position = 0;
                w12.Expand = false;
                w12.Fill = false;
                // Container child vbox1.Gtk.Box+BoxChild
                Gtk.HPaned w13 = new Gtk.HPaned();
                w13.Position = 130;
                w13.CanFocus = true;
                w13.Events = ((Gdk.EventMask)(0));
                w13.Name = "hpaned2";
                // Container child hpaned2.Gtk.Paned+PanedChild
                Gtk.ScrolledWindow w14 = new Gtk.ScrolledWindow();
                w14.VscrollbarPolicy = ((Gtk.PolicyType)(1));
                w14.HscrollbarPolicy = ((Gtk.PolicyType)(1));
                w14.CanFocus = true;
                w14.Events = ((Gdk.EventMask)(0));
                w14.Name = "scrolledwindow1";
                // Container child scrolledwindow1.Gtk.Container+ContainerChild
                Gtk.TreeView w15 = new Gtk.TreeView();
                w15.EnableSearch = false;
                w15.CanFocus = true;
                w15.Events = ((Gdk.EventMask)(0));
                w15.Name = "treeview1";
                bindings["treeview1"] = w15;
                w14.Add(w15);
                bindings["scrolledwindow1"] = w14;
                w13.Add(w14);
                Gtk.Paned.PanedChild w17 = ((Gtk.Paned.PanedChild)(w13[w14]));
                w17.Resize = false;
                // Container child hpaned2.Gtk.Paned+PanedChild
                Gtk.ScrolledWindow w18 = new Gtk.ScrolledWindow();
                w18.VscrollbarPolicy = ((Gtk.PolicyType)(1));
                w18.HscrollbarPolicy = ((Gtk.PolicyType)(1));
                w18.CanFocus = true;
                w18.Events = ((Gdk.EventMask)(0));
                w18.Name = "scrolledwindow2";
                // Container child scrolledwindow2.Gtk.Container+ContainerChild
                Gtk.TreeView w19 = new Gtk.TreeView();
                w19.CanFocus = true;
                w19.Events = ((Gdk.EventMask)(0));
                w19.Name = "treeview2";
                bindings["treeview2"] = w19;
                w18.Add(w19);
                bindings["scrolledwindow2"] = w18;
                w13.Add(w18);
                bindings["hpaned2"] = w13;
                w10.Add(w13);
                Gtk.Box.BoxChild w22 = ((Gtk.Box.BoxChild)(w10[w13]));
                w22.Position = 1;
                bindings["vbox1"] = w10;
                cobj.Add(w10);
                cobj.DefaultWidth = 695;
                cobj.DefaultHeight = 439;
                bindings["MainWindow"] = cobj;
                w11.Show();
                w15.Show();
                w14.Show();
                w19.Show();
                w18.Show();
                w13.Show();
                w10.Show();
                cobj.Show();
                cobj.DeleteEvent += ((Gtk.DeleteEventHandler)(System.Delegate.CreateDelegate(typeof(Gtk.DeleteEventHandler), cobj, "OnDeleteEvent")));
                w4.Activated += ((System.EventHandler)(System.Delegate.CreateDelegate(typeof(System.EventHandler), cobj, "OnOpenActivated")));
                w5.Activated += ((System.EventHandler)(System.Delegate.CreateDelegate(typeof(System.EventHandler), cobj, "OnSaveActivated")));
                w7.Activated += ((System.EventHandler)(System.Delegate.CreateDelegate(typeof(System.EventHandler), cobj, "OnQuitActivated")));
                w9.Activated += ((System.EventHandler)(System.Delegate.CreateDelegate(typeof(System.EventHandler), cobj, "OnAboutActivated")));
                w15.CursorChanged += ((System.EventHandler)(System.Delegate.CreateDelegate(typeof(System.EventHandler), cobj, "OnTreeview1CursorChanged")));
            }
            System.Reflection.FieldInfo[] fields = obj.GetType().GetFields(((System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic) | System.Reflection.BindingFlags.Instance));
            for (int n = 0; (n < fields.Length); n = (n + 1)) {
                System.Reflection.FieldInfo field = fields[n];
                object widget = bindings[field.Name];
                if (((widget != null) && field.FieldType.IsInstanceOfType(widget))) {
                    field.SetValue(obj, widget);
                }
            }
        }
    }
    
    internal class ActionGroups {
        
        public static Gtk.ActionGroup GetActionGroup(System.Type type) {
            return Stetic.ActionGroups.GetActionGroup(type.FullName);
        }
        
        public static Gtk.ActionGroup GetActionGroup(string name) {
            return null;
        }
    }
}
